-- Creating Tables

CREATE TABLE CUSTOMER
(
    CUST_ID BIGSERIAL NOT NULL PRIMARY KEY,
    CUST_NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100),
    PINCODE NUMERIC(6,0) NOT NULL CHECK (PINCODE > 100000 AND PINCODE <999999),
    PHONE_NO NUMERIC(10,0) NOT NULL CHECK (PHONE_NO > 5555555555 AND PHONE_NO <9999999999),
);

ALTER TABLE CUSTOMER ADD COLUMN CART_ID INT;
ALTER TABLE CUSTOMER ADD FOREIGN KEY (CART_ID) REFERENCES CART (CART_ID);

CREATE TABLE PAYMENT
(
    PAYMENT_ID BIGSERIAL NOT NULL PRIMARY KEY,
    PAYMENT_DATE DATE,
    COUPON_APPLIED VARCHAR(4) NOT NULL CHECK(COUPON_APPLIED IN('YES', 'NO')),
    TOTAL_AMT NUMERIC(6,2),
    PAYMENT_METHOD VARCHAR(50) NOT NULL CHECK(PAYMENT_METHOD IN('CASH ON DELIVERY', 'CREDIT/DEBIT CARD', 'E-WALLETS', 'NETBANKING')),
    REFERENCES CUSTOMER(CUST_ID),
    REFERENCES CART(CART_ID)
);
ALTER TABLE PAYMENT ADD CONSTRAINT POSITIVE_AMOUNT CHECK(TOTAL_AMT > 0);

ALTER TABLE PAYMENT ADD COLUMN CART_ID INT;
ALTER TABLE PAYMENT ADD COLUMN CUST_ID INT;
ALTER TABLE PAYMENT ADD FOREIGN KEY (CART_ID) REFERENCES CART (CART_ID);
ALTER TABLE PAYMENT ADD FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (CUST_ID);

ALTER TABLE PAYMENT
DROP CONSTRAINT payment_shop_id_fkey;
ALTER TABLE PAYMENT
DROP CONSTRAINT payment_product_id_fkey;
ALTER TABLE PAYMENT
DROP CONSTRAINT payment_cart_id_fkey1;

CREATE TABLE CART
(
    CART_ID BIGSERIAL NOT NULL PRIMARY KEY,
    ITEMS NUMERIC(15) NOT NULL,
    WISHLISTED INT,
    DELIVERY_DATE DATE NOT NULL,
    REFERENCES PRODUCTS(PRODUCT_ID)
);
ALTER TABLE CART ADD COLUMN PRODUCT_ID INT;
ALTER TABLE CART ADD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID) ON DELETE CASCADE;

CREATE TABLE PRODUCTS
(
    PRODUCT_ID BIGSERIAL NOT NULL PRIMARY KEY,
    TYPE VARCHAR(20) NOT NULL,
    QTY NUMERIC(4) NOT NULL,
    GENDER VARCHAR(7) NOT NULL,
    AGE_GROUP VARCHAR(20) NOT NULL CHECK(AGE_GROUP IN('INFANT','CHILDREN', 'ADULT')),
    COST NUMERIC(5,2) NOT NULL,
    COMMISSION_PERCENT NUMERIC(3,2) NOT NULL,
    REFERENCES MEDICINE_SHOP(SHOP_ID)
);
ALTER TABLE PRODUCTS ADD CONSTRAINT GENDER_CONSTRAINT CHECK(GENDER IN('MALE', 'FEMALE'));
ALTER TABLE PAYMENT ADD COLUMN SHOP_ID INT;
ALTER TABLE PAYMENT ADD FOREIGN KEY (SHOP_ID) REFERENCES MEDICINE_SHOP (SHOP_ID) ON DELETE CASCADE;

-- MEDICINE_SHOP Updated in DB

CREATE TABLE MEDICINE_SHOP
(
    SHOP_ID BIGSERIAL NOT NULL PRIMARY KEY,
    SHOP_NAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(100) ,
    PHONE_NO NUMERIC(10,0) NOT NULL CHECK (PHONE_NO > 5555555555 AND PHONE_NO < 9999999999),
);

