-- Creating Tables

CREATE TABLE CUSTOMER
(
    CUST_ID BIGSERIAL NOT NULL PRIMARY KEY,
    CUST_NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100),
    PINCODE NUMERIC(6,0) NOT NULL CHECK (PINCODE > 100000 AND PINCODE <999999),
    PHONE_NO NUMERIC(10,0) NOT NULL CHECK (PHONE_NO > 5555555555 AND PHONE_NO <9999999999),
    REFERENCES CART(CART_ID)
);

CREATE TABLE PAYMENT
(
    PAYMENT_ID BIGSERIAL NOT NULL PRIMARY KEY,
    PAYMENT_DATE DATE,
    -- COUPON_APPLIED
    -- IN
    -- ('YES', 'NO'),
    TOTAL_AMT NUMERIC
    (6,2),
    -- PAYMENT_METHOD IN
    -- ('CASH ON DELIVERY', 'CREDIT/DEBIT CARD', 'E-WALLETS', 'NETBANKING'),
    REFERENCES CUSTOMER
    (CUST_ID),
    REFERENCES CART
    (CART_ID)
);

CREATE TABLE CART
(
    CART_ID BIGSERIAL NOT NULL PRIMARY KEY,
    ITEMS NUMERIC(15) NOT NULL,
    WISHLISTED INT,
    DELIVERY_DATE DATE NOT NULL,
    REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE PRODUCTS
(
    PRODUCT_ID BIGSERIAL NOT NULL PRIMARY KEY,
    TYPE VARCHAR(20) NOT NULL,
    QTY NUMERIC(4),
    GENDER VARCHAR(7) NOT NULL,
    -- AGE_GROUP VARCHAR
    -- IN
    -- ('INFANT','CHILDREN', 'ADULT'),
    COST NUMERIC(5,2) NOT NULL,
    COMMISSION_PERCENT NUMERIC(3,2) NOT NULL,
    REFERENCES MEDICINE_SHOP(SHOP_ID)
);

CREATE TABLE MEDICINE_SHOP
(
    SHOP_ID BIGSERIAL NOT NULL PRIMARY KEY,
    SHOP_NAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(100) ,
    PHONE_NO NUMERIC(10,0) NOT NULL CHECK (PHONE_NO > 5555555555 AND PHONE_NO <9999999999),
);

-- Inseting Values

insert into customer
    (cust_name, address, pincode, phone_no)
values('Rishabh Dev', 'Rajaji Nagar', 560010, 9234511234);
insert into customer
    (cust_name, address, pincode, phone_no)
values('Sanjana Sharma', 'MoTown, Chandigarh', 230410, 9232231234);

